package markup;

public enum MdSymbolType {
    EMPHASIS_SYMBOL_UNDERLINE,
    EMPHASIS_SYMBOL_STAR,
    STRONG_SYMBOL_UNDERLINE,
    STRONG_SYMBOL_STAR,
    STRIKEOUT_SYMBOL,
    CODE_SYMBOL,
    CODE_SYMBOL_WR
}
